import "@/styles/globals.css";
import { Inter } from "next/font/google";

import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" className={cn("bg-red-500", inter.className)}>
			<body className={cn("min-h-screen")} suppressHydrationWarning={true}>
				{children}
			</body>
		</html>
	);
}
