import "@/styles/globals.css";
import { Inter } from "next/font/google";

import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" className={cn("fixed inset-0 bg-gradient-radial from-lime-450 from-60% via-yellow-350 via-90% to-red-450 to-100% font-fira-sans text-xl", inter.className)}>
			<body suppressHydrationWarning={true}>
				<Navbar />

				<main>{children}</main>
			</body>
		</html>
	);
}
